FROM python:3.10-slim

WORKDIR /app
COPY dashboard_ui/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONPATH=/app
CMD ["streamlit", "run", "dashboard_ui/app.py", "--server.port=8501", "--server.address=0.0.0.0"]