FROM python:3.10-slim

WORKDIR /app
COPY detection_service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONPATH=/app
CMD ["uvicorn", "detection_service.main:app", "--host", "0.0.0.0", "--port", "8001"]